#! /bin/sh
gap=16
PANEL_HEIGHT=24
export gap
export PANEL_HEIGHT

. "${HOME}/.profile"

pgrep -x sxhkd > /dev/null || sxhkd &
${HOME}/.config/bspwm/autostart &

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config top_padding $(PANEL_HEIGHT-$gap)
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding 0

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

. "${HOME}/.cache/wal/colors.sh"
bspc config focused_border_color "$color4"
# bspc config normal_border_color "$color0"
bspc config presel_feedback_color "$color0"

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio         0.50

# Automatically query for connected Displays and add 4 monitors for each

MONITORS=$(bspc query -M --names)

set -- $MONITORS
while [-n "$1"]; do
  bspc monitor "$1" -d 1 2 3 4 
  shift
done

bspc rule -a screenkey --unmanage
bspc rule -a google-chrome-stable private=on
bspc rule -a midori private=on
bspc rule -a gnome-pie border=off manage=off
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off

##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
