backend = "fastresize"
color_space = "lch"
palette = "dark"
check_contrast = true

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/colors.conf'
ghostty.template = 'colors-ghostty.conf'
ghostty.target = '~/.config/ghostty/themes/wallust.conf'
mako.template = 'colors-mako'
mako.target = '~/.config/mako/colors'
