# xsecurelock options
export XSECURELOCK_SAVER=saver_xscreensaver
export XSECURELOCK_PASSWORD_PROMPT=disco
XSECURELOCK_FONT='Noto Serif CJK JP'
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_SINGLE_AUTH_WINDOW=1
export XSECURELOCK_AUTH_TIMEOUT=30 
